# Project information
site_name: Plume
site_url: https://plume-oss.github.io/plume-docs/
site_author: David Baker Effendi
site_description: >-
  A Soot-based, open-source code-property graph (CPG) analysis 
  library to project and incrementally analyze the CPG of programs
  in graph databases.
# Repository
repo_name: plume-oss
repo_url: https://github.com/plume-oss
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 David Baker Effendi

plugins:
  - search

theme:
  language: 'en'
  name: material
  palette:
    scheme: default
    primary: cyan
    accent: deep orange
  logo: assets/images/logo-white.png
  favicon: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github

nav:
  - Introduction: 'index.md'
  - 'Getting Started':
      - 'Basic Usage': 'getting-started/basic-usage.md'
      - 'Architectural Overview': 'getting-started/architectural-overview.md'
  - 'Plume Basics':
      - 'Code Property Graph': 'plume-basics/code-property-graph.md'
      - 'Taint Analysis': 'plume-basics/taint-analysis.md'
      - 'Incremental Updates': 'plume-basics/incremental.md'
  - 'Storage Backends':
      - 'Introduction': 'storage-backends/introduction.md'
      - 'TinkerGraph': 'storage-backends/tinkergraph.md'
      - 'OverflowDB': 'storage-backends/overflowdb.md'
      - 'JanusGraph': 'storage-backends/janusgraph.md'
      - 'TigerGraph': 'storage-backends/tigergraph.md'
      - 'Amazon Neptune': 'storage-backends/neptune.md'
      - 'Neo4j': 'storage-backends/neo4j.md'
  - 'ScalaDoc API': 'scala-doc.md'

markdown_extensions:
  - attr_list
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.details
  - markdown.extensions.admonition